name: Test & Publish Allure to GitHub Pages

on:
  push:
    branches: [ master ]     # your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Run all shell steps from the selenium/ subfolder
defaults:
  run:
    working-directory: selenium

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-${{ runner.os }}-

      - name: Run tests (produces RAW Allure into allure-results/)
        run: mvn -B -DskipTests=false test

      - name: Generate Allure HTML (to reports/allure-report-<ts>/)
        run: mvn -B io.qameta.allure:allure-maven:2.12.0:report

      - name: Collect HTML into public/runs/<run_number> + latest + index
        run: |
          set -e
          RUN_ID="${{ github.run_number }}"
          REPORT_DIR="$(ls -td reports/allure-report-* | head -1)"
          echo "Latest HTML report: $REPORT_DIR"

          # Build a Pages-friendly folder at repo root (../public)
          mkdir -p ../public/runs/"$RUN_ID"
          cp -r "$REPORT_DIR"/* "../public/runs/$RUN_ID/"

          # Latest redirect
          mkdir -p ../public/latest
          echo '<!doctype html><meta http-equiv="refresh" content="0; url=../runs/'"$RUN_ID"'/index.html">' > ../public/latest/index.html

          # Simple index listing all runs
          mkdir -p ../public
          {
            echo '<!doctype html><html><head><meta charset="utf-8"><title>Allure Runs</title>'
            echo '<style>body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem} a{color:#0a58ca;text-decoration:none} li{margin:.4rem 0}</style></head><body>'
            echo '<h1>Allure Reports</h1>'
            echo '<p><a href="latest/">Latest report</a></p>'
            echo '<h2>History</h2><ul>'
            for d in $(ls -td ../public/runs/* 2>/dev/null | sed 's|../public/||'); do
              n=$(basename "$d")
              echo "<li><a href=\"$d/index.html\">Run #$n</a></li>"
            done
            echo '</ul></body></html>'
          } > ../public/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public   # <== this is ../public relative to selenium/ because upload-pages-artifact resolves from repo root

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
